apiVersion: apps/v1
kind: Deployment
metadata:
  name: vessel-consumer-worker
  namespace: supplychain
  labels:
    app: vessel-consumer-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vessel-consumer-worker
  template:
    metadata:
      labels:
        app: vessel-consumer-worker
    spec:
      serviceAccountName: supplychain-platform
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
      containers:
        - name: vessel-consumer-worker
          image: 402275401431.dkr.ecr.us-east-1.amazonaws.com/supplychain-platform/vessel-consumer-worker:v3
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: supplychain-config
            - secretRef:
                name: supplychain-secrets
          readinessProbe:
            exec:
              command: ["python", "-c", "import os; os.kill(1, 0)"]
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            exec:
              command: ["python", "-c", "import os; os.kill(1, 0)"]
            initialDelaySeconds: 15
            periodSeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop: ["ALL"]
